# Generated by Django 5.2.12 on 2026-04-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not applicable"),
                    ("vet", "Veterinarian"),
                    ("groomer", "Groomer"),
                ],
                default="",
                help_text="For staff accounts: vet vs grooming portal access.",
                max_length=20,
            ),
        ),
    ]
