# Generated by Django 5.2.12 on 2026-04-07 04:39

from django.db import migrations, models


def migrate_vaccination_to_yes_no(apps, schema_editor):
    Pet = apps.get_model("pets", "Pet")
    for p in Pet.objects.all():
        v = (getattr(p, "vaccination_status", None) or "").strip().lower()
        if v in ("yes", "y", "true", "1", "vaccinated"):
            p.vaccination_status = "yes"
        else:
            p.vaccination_status = "no"
        p.save(update_fields=["vaccination_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="weight",
            new_name="weight_kg",
        ),
        migrations.AddField(
            model_name="pet",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="pets/"),
        ),
        migrations.RunPython(migrate_vaccination_to_yes_no, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pet",
            name="vaccination_status",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=10
            ),
        ),
    ]
