# Generated by Django 5.2.12 on 2026-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_profile_staff_and_pet_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
            ),
        ),
    ]
